name: 刷步数

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: */30 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: |
        pip install -r requirements.txt
        python3 weibo.py
    - name: Upload to this repo
      run: |
        git config --global user.name "ysnsn"
        git config --global user.email "2746130558@qq.com" 
        git add . 
        git commit -m 'upload '  
        git push -u origin master
